### ISSUE TITLE
Support for configuration properties not covered by CamundaBpmProperties

### ISSUE THREAD

**Issue by osteinhauer** [camunda/camunda-bpm-spring-boot-starter#138]
Because it is useless to support all `(Spring)ProcessEngineConfiguration` setters directly we can provide a generic property support. The properties should be applied before default configurations.

For example to set the `batchPollTime` property in a `application.yml` it would look like:

```
camunda:
  bpm:
    generic-properties:
      ignore-invalid-fields: false
      ignore-unknown-fields: false
      properties:
        batch-poll-time: 90
```

Besides it would reduce the need to implement configuration classes.
